fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    apt:    git://github.com/puppetlabs/puppetlabs-apt.git
    python: git://github.com/stankevich/puppet-python.git